export const TabNav = {
  HomeTab: 'HomeTab',
  ExploreTab: 'ExploreTab',
  CreateTab: 'CreateTab',
  FavoritesTab: 'FavoritesTab',
  ChatTab: 'ChatTab',
  ProfileTab: 'ProfileTab',
  FriendsTab: 'FriendsTab',
};

export const StackNav = {
  Auth: 'Auth',
  TabBar: 'TabBar',
  Splash: 'Splash',
  Login: 'Login',
  Register: 'Register',
  onBoarding: 'onBoarding',
  ProfileTab: 'profileTab',
  SetUpProfile: 'SetUpProfile',
  ProfileInformation: 'ProfileInformation',
  EditUsername: 'EditUsername',
  ForgotPassword: 'ForgotPassword',
  VerifyProfileEmail: 'VerifyProfileEmail',
  CreateNewPassword: 'CreateNewPassword',
  Privacy: 'Privacy',
  PrivacyPolicy: 'PrivacyPolicy',
  HelpCenter: 'HelpCenter',
  Security: 'Security',
  Language: 'Language',
  Birthday: 'Birthday',
  Location: 'Location',
  Setting: 'Setting',
  EditProfile: 'EditProfile',
  Message: 'Message',
  Chat: 'Chat',
  Call: 'Call',
  Sound: 'Sound',
  Report: 'Report',
  ProfileDetail: 'ProfileDetail',
  Suggested: 'Suggested',
  ManageAccount: 'ManageAccount',
  QrCode: 'QrCode',
  SoundCategory: 'SoundCategory',
  HashtagCategory: 'HashtagCategory',
  TrendingSound: 'TrendingSound',
  TrendingHashtag: 'TrendingHashtag',
  AddAddress: 'AddAddress',
  AddNewCard: 'AddNewCard',
  Address: 'Address',
  HelpCenter: 'HelpCenter',
  Language: 'Language',
  NotificationSetting: 'NotificationSetting',
  Payment: 'Payment',
  PrivacyPolicy: 'PrivacyPolicy',
  Security: 'Security',
  InviteFriends: 'InviteFriends',
  Chat: 'Chat',
  Notification: 'Notification',

  PopularEvent: 'PopularEvent',
  EventDetail: 'EventDetail',
  GalleryPreEvent: 'GalleryPreEvent',
  Organizer: 'Organizer',
  GoingUser: 'GoingUser',
  BookEvent: 'BookEvent',
  BookSeat: 'BookSeat',
  ReviewSummary: 'ReviewSummary',
  MyEvents : ' MyEvents',
};
